# Generated by Django 2.1.3 on 2018-11-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20181127_2047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='book',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='book',
            name='suggested',
            field=models.BooleanField(default=False),
        ),
    ]
